Async bounded pub queue for sessions
Azure/iotedge-broker pull request #21
Opened 2021-11-10 18:01 UTC by nyanzebra

Makes channels in sessions be bounded by resource limits and uses a lockless bounded async channel implementation.

Went ahead and made the subscription table be wrapped in a Arc + RwLock for eventual multi-threading support.

2021-11-10 21:21 UTC, vadim-kovalyov requested changes
I think you're trying to do what I also tried in the beginning. The tx session end should not be blocking or we should not "await" on that, since it will block the broker.

Also, as a result you want `apply` function to be async, but that requires all sorts of changes, including a lock in `SubscriptionTable`. But `SubscriptionTable` need to remain lock free as well.

I think that might not be a right approach. I think we need to continue to have non-async tx end of session channel, and just return an `Err` immediately if session is full. Also, if session is full - it needs to be dropped (the same way IoT Hub does that today).

2021-11-10 22:44 UTC, vadim-kovalyov commented on data-plane/mqtt-broker/src/subscription/trie.rs
> +                    .collect::<Vec<_>>()
isn't that an unnecessary Vec allocation? :)

2021-11-10 23:01 UTC, nyanzebra commented on data-plane/mqtt-broker/src/subscription/trie.rs
> +                    .collect::<Vec<_>>()
Yeah, can just move up the for_each

2021-11-11 06:39 UTC, vadim-kovalyov approved these changes

2021-11-11 06:39 UTC, merged