Add runtime.
Azure/iotedge-broker pull request #3
Opened 2021-07-26 04:16 UTC by arsing

This commit adds:

- `runtime` - A runtime library.
- `broker` - A broker binary that uses `runtime`.

Currently the `runtime` crate has a stub implementation of a session - it only
services MQTT 3.1 clients, and even for them it barely acts as a broker.
Once a proper session is implemented (in a separate crate),
this stub should be replaced with that.

---

There are two major differences from the previous `no_broker` repository's
test implementation:

1. All poll* API has been replaced with API that returns `Future`s.
   The `no_broker` version of `BufferPoll::poll_take` was vulnerable to
   zombie wakers from tasks that were dropped before ever receiving
   the buffer they asked for, and from tasks that called `poll_take`
   multiple times. The way to combat this is to have taking be a `Future`,
   whose `poll` registers the current polling task's waker (overwriting
   the previous one if any) and whose `Drop` frees the waker registration.

2. `Session` decodes the incoming buffers, not `Reader`. This is needed because
   `Session` is the one with knowledge of what protocol a particular client
   is using.

2021-07-26 18:55 UTC, zasherif requested changes
Would you please add the traits, we have in the abstractions and implement them? The whole purpose of this is to be able to change the implementation as we move forward, and we need traits for that. You can change the signature of the functions as you find appropriate.

I don't think that the Session decoding the packet is portable to other protocols or changes in implementation. We designed the Reader to be stateful if needed, so it's okay to maintain a protocol version there and pass it to the session.

2021-07-26 19:38 UTC, zasherif requested changes
Halfway through this PR, will add more comments later.

2021-07-26 19:38 UTC, zasherif commented on runtime/src/acceptor.rs
> +    pub(crate) fn accept(&self) -> impl Future<Output = io::Result<Rc<Reader>>> {
Would you please modify the Acceptor trait to return the future (of user defined output)?

2021-07-26 19:38 UTC, zasherif commented on runtime/src/acceptor.rs
> +    session: Rc<Session>,
The acceptor shall produce a Connection (not a Session), why does it hold on a session? A Connection is the object that shall creates a session.

2021-07-26 19:38 UTC, zasherif commented on runtime/src/buffer_pool.rs
> +const BUFFER_LEN: usize = 128;
We will need to add methods, or a Factory for the buffer pool (here and in traits) to modify these during constructions from a ResourceLimit object.

2021-07-26 19:38 UTC, zasherif commented on runtime/src/buffer_pool.rs
> +struct BufferPoolTake {
Would you please add a docstring here describing the inner working of this BufferPoolTake struct?

2021-07-26 19:38 UTC, zasherif commented on broker/src/main.rs
> +    runtime.register_acceptor(acceptor).unwrap();
We need to implement a register_listener (to be able to extend over multiple ports/protocols). Even if it does nothing but adding "one" listeners to one acceptor in this implementation, we will need that to extend this runtime.

2021-07-26 19:38 UTC, zasherif commented on runtime/src/lib.rs
> +        let pending_wake_fd = eventfd(0, EfdFlags::EFD_CLOEXEC | EfdFlags::EFD_NONBLOCK)?;
Do we really need an eventfd wait/notify with read/writes sys-calls to implement a waker (in the same process)?

2021-07-26 19:38 UTC, zasherif commented on runtime/src/lib.rs
> +            reader_fd as _,
I am not of a rust expert, but this shall simply point to whatever context data structure associated with the reader_fd? Is this possible instead of maintaining a data structure of readers.

2021-07-26 19:38 UTC, zasherif commented on runtime/src/lib.rs
> +                acceptor_fd as _,
ditto: this usually point to an acceptor context (which holds the actual acceptor), instead of maintaining a separate data structure that maps a FD to the acceptor !

2021-07-26 19:38 UTC, zasherif commented on runtime/src/waker.rs
> +        pending_wakes.insert(self.fd);
So we have a FD for each waker? What will happen if stress-test this runtime, we run out of FDs ?

2021-07-28 18:51 UTC, vadim-kovalyov reviewed
Still reviewing, but here are few minor comments... Will continue after lunch.

2021-07-28 18:51 UTC, vadim-kovalyov commented on runtime/src/lib.rs
> +                    if let Some(f) = write_future {
not sure if it matters here, but should we try to write first, before read?

2021-07-28 18:51 UTC, vadim-kovalyov commented on runtime/src/lib.rs
> +    session: Rc<Session>,
I was thinking about better naming for this. I thought maybe `Broker`, but it seems to me that it deals with a lot more than just brokering. So how about `MqttServer`? Also, later, we could extract common interface (trait) for it and have `CoapServer` as well... what do you think?

2021-07-28 19:19 UTC, arsing commented on runtime/src/lib.rs
> +    session: Rc<Session>,
You're right, I forgot we talked about `Session` -> `Broker` and `Runtime` -> `Worker`. I'll make that change. I don't have an opinion on `Broker` vs `Server` (MQTT spec only talks about servers, and brokering is the only job the server does, so they're synonymous anyway?)

re: `MqttBroker` vs `Broker`, the implementation can have submodules of `MqttBroker` and `CoapBroker` to organize the code, but from the `Worker`'s and `Reader`'s perspective it's just the entrypoint to I/O of bytes regardless of the protocol. So the top-level "service" that the `Worker` and `Reader` deal with would still be `Broker`.

2021-07-28 20:45 UTC, vadim-kovalyov commented on runtime/src/waker.rs
> +        pending_wakes.insert(self.fd);
If I understand correctly, we only have a single `pending_waker_fd` for signaling the runtime. The `pending_wakes` just keeps the list of FDs that were re-awoken. So no extra FDs apart from connected clients and listeners.

2021-07-28 21:13 UTC, vadim-kovalyov approved these changes
LGTM overall. One question about `remaining_length > new_filled_len` in `session.rs`

It also would be great if we can fill out missing code docs on key components like Reader/Writer/Broker/Worker with their goals and responsibilities.

2021-07-28 21:13 UTC, vadim-kovalyov commented on runtime/src/session.rs
> +            }
I'm not sure I understand this logic in the context of `Reader`. If we don't have enough space in the buffer, we return `Ok((())`, but then `Reader` will just continue the loop and will call `session.recv()` again. That seems not right.

2021-07-28 21:13 UTC, vadim-kovalyov commented on runtime/src/session.rs
> +    pub(crate) fn unregister_reader(&self, fd: RawFd) {
nit: I would call it `remove`.

2021-07-28 22:08 UTC, nyanzebra commented on runtime/src/acceptor.rs
> +use crate::{Reader, Session};
As a future todo we should add doc comments to everything that is public to explain how they work. Just one sentence above each public thing will make life much easier in the future when we forget things or someone new comes in :)

Once again, this can be an action item for later :)

2021-07-28 22:15 UTC, nyanzebra commented on runtime/src/acceptor.rs
> +        let inner = TcpListener::bind(addr)?;
I am a bit confused by your statement @zasherif 

From the design doc:
```
- __Listener__/__Acceptor__: A listening socket used to accept incoming
  connections (i.e., using the 'listen' syscall). The Runtime invokes an
  Acceptor when a Listener is ready with events. The Acceptor creates Stream and
  Sink objects corresponding to the accepted connection
  ```

Shouldn't a listener trigger an acceptor? Maybe I have this all mixed up... but trying to compare this to the doc that was written to match things up.

2021-07-28 22:15 UTC, zasherif commented on runtime/src/waker.rs
> +        pending_wakes.insert(self.fd);
Even if it's the case we still have sys-calls to just signal the wakers.

2021-07-28 22:17 UTC, nyanzebra commented on runtime/src/acceptor.rs
> +    session: Rc<Session>,
You mean like this?

```
pub struct MyAcceptor {
 runtime_handle: MyRuntimeHandle,
 connection_pool: MyConnectionPool,
 sender: MySender,
 receiver: MyReceiver,
}
```

2021-07-28 22:19 UTC, nyanzebra commented on runtime/src/buffer_pool.rs
> +const BUFFER_LEN: usize = 128;
I think this can be done in a separate PR? This PR and Arnav's other one were both kinda long... but maybe I am just slow reviewing PRs :P

2021-07-28 22:20 UTC, nyanzebra commented on runtime/src/buffer_pool.rs
> +                        // TODO:
Instead of just a TODO, we could put an issue on the repo as a todo list? Just an idea if you think we might forget about these at some point :)

2021-07-28 22:22 UTC, zasherif commented on runtime/src/acceptor.rs
> +        let inner = TcpListener::bind(addr)?;
I mean the Listener should not be a direct dependency on TcpListener of Tokyo.

Like this
```rust
struct Listener(TcpListener) {
    ...
}
```

2021-07-28 22:24 UTC, zasherif commented on runtime/src/acceptor.rs
> +    session: Rc<Session>,
Yes this, or a something similar. The Acceptor - in the transport layer - should not depend on the Session directly this way, the session comes from higher layer (e.g. a session table).

2021-07-28 22:27 UTC, nyanzebra commented on runtime/src/buffer_pool.rs
> +        BufferPoolTake {
IAt least to me, right now, this seems to be a way to make sure we can add Drop semantics? Also do you mind changing the name of the struct? Maybe something like BufferPoolTakePoller to try to help indicate this a struct that does the work of taking from the pool?

2021-07-28 22:32 UTC, vadim-kovalyov commented on runtime/src/acceptor.rs
> +    session: Rc<Session>,
I think that Session is just a bad naming here. It should rather be called Server or Broker. See the discussion below https://github.com/Azure/iotedge-broker/pull/3#discussion_r678538920

2021-07-28 22:49 UTC, nyanzebra commented on runtime/src/lib.rs
> +                } else if let Some((reader, read_future, write_future)) = self.readers.get_mut(&fd)
Could you give a quick summary on why this is `else if` and why we don't want to register readers for an fd and get futures for the fd from readers in the same loop?

2021-07-28 22:53 UTC, vadim-kovalyov commented on runtime/src/lib.rs
> +                } else if let Some((reader, read_future, write_future)) = self.readers.get_mut(&fd)
I believe if `fd` is in `self.acceptors`, then it can't be in `self.readers`,  b/c an FD can be either acceptor or reader.

2021-07-28 22:54 UTC, nyanzebra commented on runtime/src/lib.rs
> +                    if let Some(f) = write_future {
I don't think it will matter in the event loop, and am sure Arnav can correct me if I am wrong; but, since we register readers to get data into buffers above this we could have a situation where things are pending on available buffers that can be written out (assuming this is the concern). We will then see that the read_future is pending and then do the write_future which I suspect (haven't double checked this) would release the buffer for the read_future to continue. So worst case scenario the read can continue next loop which should give the rest of the system some time to move buffers around :)

TLDR; I doubt it matters which comes first, but maybe we can put a comment or two for quick reference?

2021-07-28 22:55 UTC, nyanzebra commented on runtime/src/lib.rs
> +    >,
This might be a nice typedef :)

2021-07-29 17:50 UTC, vadim-kovalyov commented on runtime/src/lib.rs
> +    session: Rc<Session>,
@arsing  If you don't have strong opinion on `Broker` vs `Server`, I think I would like `Server` more, and I'm planning to have `Broker` as a sub-component of `Server`.

2021-07-29 20:38 UTC, vadim-kovalyov commented on runtime/src/session.rs
> +    #[allow(clippy::await_holding_refcell_ref)]
I've been thinking about this more... Is it possible that write will `await` on buffer, but at the same time the `recv()` is called? Have you tested this?

2021-07-29 21:22 UTC, arsing commented on runtime/src/session.rs
> +        stream.set_nonblocking(true)?;
Done.

2021-07-29 21:22 UTC, arsing commented on runtime/src/lib.rs
> +    session: Rc<Session>,
Done.

2021-07-29 21:26 UTC, arsing commented on runtime/src/session.rs
> +            }
Eventually the Reader's buffer will fill up but Server will still refuse to read any bytes from it by early-returning. Then Reader will copy it into a new buf with more space (`// Not enough remaining unfilled space.`)

I've added a comment.

(There is still the problem of receiving a message that is bigger than the biggest buffer, which will get solved when in the future we add the API to request buffers with specific minimum length *and* implement the feature for the buffer pool to have floating dynamic buffers.)

2021-07-29 21:29 UTC, arsing commented on runtime/src/session.rs
> +    pub(crate) fn unregister_reader(&self, fd: RawFd) {
`unregister` is the opposite of `register` though. If it was `remove_reader` then the previous function should be `add_reader` ?

2021-07-29 21:32 UTC, arsing commented on runtime/src/buffer_pool.rs
> +                        // TODO:
I have a (small) preference for TODOs in the source for two reasons:

- Them getting lost isn't a problem as long as you have the clone locally, since you can just grep for `TODO`. (I always annotate them consistently as `TODO` for that reason.)

- They remain in sync with the surrounding code as it moves around or gets refactored. With a github issue you either make a link to the file in main in which case it breaks as soon as any lines shift around, or you link to a specific commit in which case there is additional work to do to check where the TODO has moved to and whether it's even still relevant.

In any case, this TODO is fresh in my mind. I'll leave this here and double-check we have a VSTS task for it.

2021-07-29 21:34 UTC, arsing commented on runtime/src/buffer_pool.rs
> +        BufferPoolTake {
Rust combinators are named this way in general. [`Iterator::map`](https://doc.rust-lang.org/stable/std/iter/trait.Iterator.html#method.map) returns `Map`, not `MapIterator`. [`futures::select`](https://docs.rs/futures/0.3.16/futures/future/fn.select.html) returns `Select`, not `SelectFuture`

2021-07-29 21:34 UTC, arsing commented on runtime/src/lib.rs
> +                } else if let Some((reader, read_future, write_future)) = self.readers.get_mut(&fd)
Yes, what Vadim said.

2021-07-29 21:39 UTC, arsing commented on runtime/src/lib.rs
> +    >,
Moved into `struct ReaderContext`, and `struct AcceptorContext` for the `acceptors` values.

2021-07-29 21:41 UTC, arsing commented on runtime/src/session.rs
> +    #[allow(clippy::await_holding_refcell_ref)]
You're right. I tested with multiple publishers but the timing always worked out that it didn't double-borrow.

2021-07-29 22:01 UTC, arsing commented on runtime/src/session.rs
> +    #[allow(clippy::await_holding_refcell_ref)]
Fixed by restructuring the code so that the `RefCell` can be dropped and reborrowed around the await.

2021-07-29 23:12 UTC, vadim-kovalyov commented on runtime/src/session.rs
> +    pub(crate) fn unregister_reader(&self, fd: RawFd) {
Runtime has `register_reader`/`unregister_reader` and it is fine and makes sense. `Session` (or rather `Server` as I'd like it to be called) deals with "connected" sockets(aka clients). There we have `accept`(client) and `remove`(client). Also, to be specific, `Server::unregister_reader` removes the whole client state from the `Server`, not just "reader".

2021-07-29 23:27 UTC, vadim-kovalyov commented on runtime/src/session.rs
> +            }
Ok, I guess I missed the fact that we don't `drain` the `buf`, but just return, so it will actually break out of the loop in reader and will continue reading from socket....

2021-07-29 23:29 UTC, nyanzebra commented on runtime/src/buffer_pool.rs
> +        BufferPoolTake {
Fair point :) I guess I never have the explicit type name for these and just never noticed till you brought this up...

2021-07-30 19:44 UTC, nyanzebra commented on runtime/src/server.rs
> +                                    // return_code: mqtt_proto::v3::ConnectReturnCode::Refused(mqtt_proto::v3::ConnectionRefusedReason::NotAuthorized),
What is this comment for?

2021-07-30 19:46 UTC, nyanzebra commented on runtime/src/server.rs
> +                    }
nit: this might be a good helper fn called like validate_init_packet(...) or something. Might also be nice to have helpers for the the V3 and V5 to make this fn less long and maybe improve readability. If don't feel like it helps then feel free to ignore this :)

2021-07-30 20:06 UTC, arsing commented on runtime/src/server.rs
> +                                    // return_code: mqtt_proto::v3::ConnectReturnCode::Refused(mqtt_proto::v3::ConnectionRefusedReason::NotAuthorized),
It's just a testing thing to switch between accepting / rejecting the client.

2021-08-02 17:19 UTC, arsing commented on runtime/src/buffer_pool.rs
> +struct BufferPoolTake {
Done.

2021-08-02 17:20 UTC, arsing commented on runtime/src/lib.rs
> +        let pending_wake_fd = eventfd(0, EfdFlags::EFD_CLOEXEC | EfdFlags::EFD_NONBLOCK)?;
As we'd discussed in the past, the option is to have an infinite-timeout epoll so all wakeups need to be delivered through fds (this implementation), or have a finite-timeout epoll and then process other wakeups (your implementation). We can switch to the latter when we get to the experimentation phase.

2021-08-02 17:27 UTC, arsing commented on runtime/src/lib.rs
> +            reader_fd as _,
Right, the equivalent of what you'd do in C is to do `Box::into_raw(Box::new(context))` (ie allocate and leak each individual context) and then `unsafe { &mut *(ptr as *mut Context) }` to view it / `unsafe { Box::from_raw(ptr) }` to drop it.

It's true that it's probably the case that the efficiency gained from not individually allocating each context (because of batched allocations when the `BTreeMap` resizes) is offset by having to do the `BTreeMap` lookup instead of just chasing the pointer. I'll change it.

2021-08-02 18:25 UTC, arsing commented on runtime/src/lib.rs
> +            reader_fd as _,
Done.

2021-08-02 18:25 UTC, arsing commented on runtime/src/lib.rs
> +                acceptor_fd as _,
Done.

2021-08-02 18:26 UTC, arsing commented on runtime/src/waker.rs
> +        pending_wakes.insert(self.fd);
>Even if it's the case we still have sys-calls to just signal the wakers.

Answered in https://github.com/Azure/iotedge-broker/pull/3#discussion_r681143343

2021-08-02 18:28 UTC, arsing commented on runtime/src/session.rs
> +    pub(crate) fn unregister_reader(&self, fd: RawFd) {
TBH even in the worker, the `Reader` is actually a `Client`, since it has both read and write futures. I've renamed that.

And yes, sorry, I missed that your comment is on server, not worker. I've renamed this to `remove_client`.

2021-08-02 18:45 UTC, arsing commented on runtime/src/server.rs
> +                    }
>Might also be nice to have helpers for the the V3 and V5

To be clear, those helpers already exist; the bulk of the `Connect`-packet-parsing is in `mqtt_proto::Connect::decode` in the next line. The reason this code and the `buf.is_empty()` check after the `mqtt_proto::Connect::decode` line exist is that `PacketMeta::decode` expects the caller to do those things. So all three callers of `PacketMeta::decode` - this code, `mqtt_proto::v3::decode` and `mqtt_proto::v5::decode` - do this.

Because the handling of what `PacketMeta` impl to use after decoding the `packet_type` and `flags` is different for all three callers, I'm not sure there's any way to DRY it.

2021-08-02 18:53 UTC, zasherif commented on runtime/src/lib.rs
> +        let pending_wake_fd = eventfd(0, EfdFlags::EFD_CLOEXEC | EfdFlags::EFD_NONBLOCK)?;
I don't think the overhead of read/write sys-call compared to any other variable based approach needs any experimentations. Would you please change that to a waker that does not depend on sys-call at all?

2021-08-02 18:53 UTC, arsing commented on runtime/src/lib.rs
> +                    if let Some(f) = write_future {
Yes, it doesn't matter, but the point about prioritizing writes over reads is good (I forgot I did the same in arsing-mqtt too). I've switched them and added a comment.

2021-08-02 19:14 UTC, arsing commented on runtime/src/buffer_pool.rs
> +                        // TODO:
Actually, my bad, I thought this was the TODO to make the buffer pool confgurable and add dynamic buffer support. Your comment is about the `Arc::new_zeroed_slice`

I don't think that should be made into a VSTS task - it's impossible to fix it until the API is stabilized in libstd.

2021-08-02 19:20 UTC, vadim-kovalyov commented on runtime/src/lib.rs
> +                }
I'm looking at the new changes and it made me think  if it is possible to get rid of interior mutability in `Reader`. Right now `TaskContext` owns the only ref to `Reader` (as far as I can see), and also owns `read_future` that can take `&mut` on Reader, right? It seems to me we don't have any other use of `Reader` anywhere else.... Or maybe I'm missing something, and it will change in the future, but I'm just trying to get rid of `RefCell` as much as possible.

2021-08-02 19:21 UTC, vadim-kovalyov commented on runtime/src/lib.rs
> +                }
If ^^ makes sense, I'm fine if we can address that in the future PR.

2021-08-02 19:27 UTC, arsing commented on runtime/src/lib.rs
> +                }
```diff,rust
-pub(crate) async fn read(self: Rc<Self>) -> io::Result<()> {
+pub(crate) async fn read(self: Rc<Self>) -> io::Result<Self> {
```

... could work. Let me try.

2021-08-02 19:49 UTC, arsing commented on runtime/src/lib.rs
> +                }
Yes, it works. Done. Only annoying this is return type needs to include `Self` in the `Err` case too, so `?` became slightly more annoying to use.

2021-08-05 22:28 UTC, nyanzebra approved these changes

2021-08-09 23:39 UTC, nyanzebra commented on traits/src/io.rs
> +}
We don't want to use the async_trait for now?

2021-08-09 23:55 UTC, nyanzebra approved these changes

2021-08-09 23:56 UTC, arsing commented on traits/src/io.rs
> +}
I'd rather keep it explicit.

2021-08-16 22:31 UTC, vadim-kovalyov reviewed
I have a question about the `traits` crate, everything else LGTM.

2021-08-16 22:31 UTC, vadim-kovalyov commented on Cargo.toml
> +    "traits",
I'm not sure that "traits" is the best name/place for those "abstractions" that we defined. I'm also not sure why `traits` crate takes dependency on `mqtt-proto`, I thought, if any, it should be the other way around.

Would it be better to spread the traits into corresponding crates? Like `Worker` goes into `runtime`, `BufferPool` into `buffer-pool`, etc...

2021-08-16 22:31 UTC, vadim-kovalyov commented on io/Cargo.toml
> +edition = "2018"
nit: it would be great to add `description` with the same text as in `docs-dev/README.md`

2021-08-16 22:41 UTC, arsing commented on Cargo.toml
> +    "traits",
I will discuss both of those points in the meeting. tl;dr is:

>I'm also not sure why traits crate takes dependency on mqtt-proto

This is temporary until I move buffer-pool types out of `mqtt-proto`

>Would it be better to spread the traits into corresponding crates?

This creates circular dependencies.

2021-08-18 18:14 UTC, varunpuranik commented on traits/Cargo.toml
> +[package]
I like this code structure... it is actually similar to edged, ea, etc... 
Just that instead of traits, can we call this crate core? It can include the traits and any core types/functionality..

2021-08-18 22:38 UTC, arsing commented on Cargo.toml
> +    "traits",
>>I'm also not sure why traits crate takes dependency on mqtt-proto
>
>This is temporary until I move buffer-pool types out of `mqtt-proto`

As we discussed in the meeting, I'll tackle this in a later PR. We definitely want `mqtt_proto::BufferPool` to move from `mqtt-proto` to `buffer-pool`, but you also said you'd still prefer to have two traits so that there's a separation between the concerns of "when I drop this buffer it returns to this pool" and "I can get a buffer from this pool".

>>Would it be better to spread the traits into corresponding crates?
>
>This creates circular dependencies.

Indeed, moving the traits to the crates as you suggested does work now, so I've done that. The circular dependencies problem was probably resolved as part of making the `Sink` traits anyway, and I just hadn't tried after that.

I did have to rename all the concrete types from `Foo` to `FooImpl` so that they don't overlap with the trait `Foo` in the same crate.

2021-08-18 22:39 UTC, arsing commented on io/Cargo.toml
> +edition = "2018"
Eh, I don't know if anyone cares about the description. It's not like we'll be publishing these to crates.io that we care about search metadata.

I would include those sentences in the crate docs, when I get around to adding more doc comments like Robert commented.

2021-08-18 22:40 UTC, arsing commented on traits/Cargo.toml
> +[package]
The `traits` crate's traits have been subsumed into the individual layer crates, so it doesn't matter now.

2021-08-18 23:49 UTC, vadim-kovalyov approved these changes
🚀

2021-08-19 00:06 UTC, closed without merging

2021-08-19 00:07 UTC, arsing commented
Merged as b41e893c1ce5a77578b33e28d01616aeb7e7f6aa