Implement tiering in the buffer pool, a tier for a dynamic buffer pool, and a size hint in `BufferSource::take`
Azure/iotedge-broker pull request #4
Opened 2021-08-23 06:11 UTC by arsing

Tiering is currently hard-coded to have one static pool and one dynamic pool.

This change also moves `mqtt_proto::BufferPool` to `buffer_pool::BufferSink`,
`mqtt_proto::{Owned, Shared}` to `buffer_pool::{Owned, Shared}`,
and `buffer_pool::BufferPool` to `buffer_pool::BufferSource`.
The mqtt-proto-specific functions on `Shared`, ie the ones that returned
`mqtt_proto::DecodeError` and `mqtt_proto::PacketIdentifier`, are still in
`mqtt-proto` as extension methods on `buffer_pool::Shared`.

Lastly, this change adds a stub implementation of reading a config file.
Currently this config file only has buffer pool parameters at the global level.
If we need per-component buffer pools and per-component buffer pool tiers
in the future, this will need to change.

2021-08-23 18:07 UTC, zasherif requested changes

2021-08-23 18:07 UTC, zasherif commented on buffer-pool/src/custom.rs
> +}
Would you please explain the inner working the dynamicbuffer pool (in reply to this comment)? I am trying to verify a couple of lines in BufferPoolTake, and I think we may have a bit of disconnect here.

2021-08-23 18:51 UTC, vadim-kovalyov approved these changes
:+1:

2021-08-23 20:20 UTC, arsing commented on broker/src/main.rs
> +        buffer_pool::BufferPoolImpl::new(static_capacity, static_len, dynamic_capacity);
`new` is fine for this since it's the only constructor. If there were multiple constructors, like say this one and another that didn't take the config as a parameter and returned a `BufferPoolImpl` with default limits, then it would be appropriate to have that one be `new` and this one be `from_config`

2021-08-23 20:22 UTC, arsing commented on broker/src/main.rs
> +    } = toml::from_slice(&config).unwrap();
I assume you meant config *mod*. But also since you want the `BufferPoolImpl` ctor take the config value, that means it can't be a mod but an entirely separate crate so that `buffer-pool` can depend on it.

So if we're going that far already we might as well do it properly, ie pull in `config-common` from the i-i-s repo to parse both `/etc/iotedge-broker/config.toml` and `/etc/iotedge-broker/config.d/*.toml` and do the whole config-unioning thing.

2021-08-23 20:32 UTC, arsing commented on buffer-pool/src/custom.rs
>                  take_futures: Slab::with_capacity(32),
Default capacity of the slab. If you mean "why is it 32" it's somewhat arbitrary. I can make it a `const`.

`futures-utils::lock::Mutex` (that I took the `slab` idea from) code creates an empty slab instead. That has the advantage of not allocating, but the disadvantage of immediately allocating when a new element is pushed into it. This is appropriate for `futures-util::lock::Mutex` since the `Mutex` doesn't know how many things will poll it and also there probably won't be a lot of them, so it is better for it to be conservative. But in our case the `BufferPool` is likely to be polled by every reader and writer, so pre-allocating some capacity to start is better.

2021-08-23 20:36 UTC, arsing commented on buffer-pool/src/custom.rs
> +}
It has a `limit` for how many bytes it can allocate in total. If it's asked to allocate a buffer of N length, it increases `used` by N. When the buffer of N bytes is returned to it, it decreases `used` by N.

I've added comments to `StaticBufferPool` and `DynamicBufferPool`

2021-08-23 20:45 UTC, arsing commented on broker/src/main.rs
> +        buffer_pool::BufferPoolImpl::new(static_capacity, static_len, dynamic_capacity);
Done.

2021-08-23 20:46 UTC, arsing commented on broker/src/main.rs
> +    } = toml::from_slice(&config).unwrap();
Done.

2021-08-23 20:46 UTC, arsing commented on broker/src/main.rs
> +        toml::from_slice(&[]).expect("cannot fail to deserialize hard-coded valid config")
Done.

2021-08-23 20:46 UTC, arsing commented on buffer-pool/src/custom.rs
>                  take_futures: Slab::with_capacity(32),
>I can make it a `const`.

Done.

2021-08-23 21:05 UTC, zasherif commented on buffer-pool/src/custom.rs
> +}
In BufferPoolTake, we allocate from DynamicBufferPool, if the Length is less than the static length. Correct? Then we immediately move to the DynamicBufferPool. From your code below and If I correctly understand this, the final effect is similar to what we have in ntex; "grow a vector of bytes to the requested length". A behavior which we wanted to avoid, or at make it user configurable.  Am I messing something?

```rust
let buf = if self.len <= inner.tiers.static_1.len {
                 inner.tiers.static_1.pool.pop_front()
             } else if inner.tiers.dynamic.used + self.len < inner.tiers.dynamic.limit {
                 inner.tiers.dynamic.used += self.len;
                 Some(arc_new_zeroed_slice(self.len))
             } else {
                 None
             };
```

2021-08-23 21:25 UTC, arsing commented on buffer-pool/src/custom.rs
>                  take_futures: Slab::with_capacity(32),
>Shouldn't this be the pool size (static_capacity)?

Oh yes, that's a good point. It should be at least the sum of all the static tiers. Then it could be a little higher to account for the dynamic tier. Maybe 2x the sum of all the static tiers?

2021-08-23 21:35 UTC, arsing commented on buffer-pool/src/custom.rs
> +}
>In BufferPoolTake, we allocate from DynamicBufferPool, if the Length is less than the static length. Correct?

No. If the length is less than the static length, we take a buffer from the static pool - `inner.tiers.static_1.pool.pop_front()`

2021-08-23 21:47 UTC, arsing commented on buffer-pool/src/custom.rs
>                  take_futures: Slab::with_capacity(32),
Actually no, it shouldn't be the sum of the static tiers' capacities. It's completely unrelated to the pool capacity. Futures for buffers that are already in capacity will resolve immediately, so their entry in the slab will be short-lived.

2021-08-23 23:14 UTC, zasherif commented on buffer-pool/src/custom.rs
> +}
Got it thanks.

2021-08-24 01:12 UTC, zasherif commented on buffer-pool/src/custom.rs
>                  take_futures: Slab::with_capacity(32),
You still need to account for buffers being used. In the worst case that's the maximum number of buffers in the static pool at least. The dynamic pool is fine, we can allocate the extra for slots for it if it's being used.

2021-08-24 01:12 UTC, zasherif approved these changes

2021-08-24 02:27 UTC, arsing commented on buffer-pool/src/custom.rs
>                  take_futures: Slab::with_capacity(32),
>In the worst case that's the maximum number of buffers in the static pool at least.

No, this is not the case. Consider a static pool with 1000 buffers.

If a client asks for 1000 buffers in series (without ever returning any of the buffers), the slab will have at most one element in it at any time, and zero at the end.

If a client asks for 3000 buffers and polls each future once so that they might either resolve or be pending, then the slab will have 2000 elements at the end.

If a client asks for 3000 buffers and then awaits all the futures with `join_all`, then the slab will initially have 3000 elements, then drop down to 2000 elements at the end.

If there are 3000 clients that ask for 3000 buffers with some parallelism, then the slab might have any number of elements between 1 and 3000.

The number of elements in the slab is not related to the number of buffers in the slab. It can be arbitrarily more.

2021-08-24 06:39 UTC, merged

2021-08-24 16:29 UTC, zasherif commented on buffer-pool/src/custom.rs
>                  take_futures: Slab::with_capacity(32),
In the last two examples you show the maximum elements in the slab is the maximum the clients can ask for. client asks for 3K buffers, and join_all, then the slab may goes up to 3K. What the client awaits. Then in this case, it's better to pre-allocate that memory in the slab and reserve this as part of our memory budget.